server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  logging:
    level:
      org.springframework.mail: DEBUG
      com.sun.mail: DEBUG   # برای Jakarta Mail


  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2

  cache:
    type: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: Parsakavianpour@gmail.com
    password: incjoupthhojzszn

    properties:
      mail.debug: true
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 952885940458-i044kv5m9hinsi3b4fg0f5nvmhj9a92t.apps.googleusercontent.com
            client-secret: GOCSPX-REPLACE_ME_IMMEDIATELY
            scope: [openid, profile, email]
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub

  data:
      redis:
        host: localhost
        port: 6379

jwt:
  secret: "super-secret-change-me-parsa-kavianpour"
  expiration-minutes: 120
